[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
dotenv = "0.15.0"
edstem = { git = "https://github.com/laggycomputer/edstem.git", features = ["serde"] }
serde = "1.0.219"
tokio = { version = "1.44.1", features = ["full"] }
